<?php

class PostMetaStorage extends DirectoryStorage {

    private $postMetaKey;
    private $postMetaVpId;

    function __construct($directory) {
        parent::__construct($directory, 'post');
    }

    function save($values) {
        $data = $this->transformToPostField($values);

        $this->postMetaKey = $values['meta_key'];
        $this->postMetaVpId = $values['vp_id'];

        $this->saveEntity($data, array($this, 'notifyOnChangeListeners'));
    }

    function delete($restriction) {
        parent::delete($restriction); // TODO: Change the autogenerated stub
    }

    function saveAll($entities) {
        foreach ($entities as $entity) {
            $data = $this->transformToPostField($entity);
            $this->saveEntity($data);
        }
    }


    protected function createChangeInfo($entity, $changeType) {
        return new PostChangeInfo('edit', $entity['vp_id'], 'postmeta', $entity['post_title']);
    }

    private function transformToPostField($values) {
        $key = sprintf('%s#%s', $values['meta_key'], $values['vp_id']);
        $data = array(
            'vp_id' => $values['vp_post_id'],
            $key => $values['meta_value']
        );
        return $data;
    }
}